spring:
  application:
    name: gangonem
  datasource:
    url: jdbc:h2:mem:testdb
  profiles:
    active: local

server:
  servlet:
    context-path: /

  port: 8080
 
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: aws
  ssl:
    key-store: ./certs/keystore.jks
    key-store-password: password
    key-store-type: jks
    key-alias: selfsigned
  port: 8443      
