spring:
  application:
    name: gangonem
  datasource:
    url: jdbc:h2:mem:testdb
  profiles:
    active: local

server:
  servlet:
    context-path: /
  port: 8080
 
---
spring:
  config:
    activate:
      on-profile: local
